"""Project initialisation for maverick — detects technology stack and writes config."""

import json
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

AVAILABLE_MODULES = [
    "nodejs",
    "typescript",
    "react",
    "fastify",
    "vitest",
    "python",
    "pytest",
    "ruff",
    "kotlin",
    "docker",
    "github-actions",
]

# Each rule is (description, check_function, module_name)
DETECTION_RULES: list[tuple[str, str]] = []  # populated dynamically


def _read_json(path: Path) -> dict:
    """Read a JSON file, returning empty dict on failure."""
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


def _read_toml(path: Path) -> dict:
    """Read a TOML file, returning empty dict on failure."""
    try:
        return tomllib.loads(path.read_text())
    except Exception:
        return {}


def _file_contains(path: Path, text: str) -> bool:
    """Check if a text file contains a string."""
    try:
        return text in path.read_text()
    except Exception:
        return False


def detect_modules(project_path: Path) -> list[str]:
    """Scan a project directory and return detected module names."""
    detected = []

    package_json = project_path / "package.json"
    tsconfig = project_path / "tsconfig.json"
    pyproject = project_path / "pyproject.toml"
    requirements = project_path / "requirements.txt"
    build_gradle = project_path / "build.gradle.kts"
    dockerfile = project_path / "Dockerfile"
    gh_workflows = project_path / ".github" / "workflows"

    # Node.js
    if package_json.exists():
        detected.append("nodejs")
        pkg = _read_json(package_json)
        deps = pkg.get("dependencies", {})
        dev_deps = pkg.get("devDependencies", {})

        # TypeScript
        if tsconfig.exists():
            detected.append("typescript")

        # React
        if "react" in deps:
            detected.append("react")

        # Fastify
        if "fastify" in deps:
            detected.append("fastify")

        # Vitest
        if "vitest" in dev_deps:
            detected.append("vitest")

    # Python
    if pyproject.exists() or requirements.exists():
        detected.append("python")

        if pyproject.exists():
            toml_data = _read_toml(pyproject)
            all_deps_str = json.dumps(toml_data)
            if "pytest" in all_deps_str:
                detected.append("pytest")
            if "ruff" in all_deps_str:
                detected.append("ruff")

        if requirements.exists():
            if _file_contains(requirements, "pytest"):
                if "pytest" not in detected:
                    detected.append("pytest")
            if _file_contains(requirements, "ruff"):
                if "ruff" not in detected:
                    detected.append("ruff")

    # Kotlin
    if build_gradle.exists():
        detected.append("kotlin")

    # Docker
    if dockerfile.exists():
        detected.append("docker")

    # GitHub Actions
    if gh_workflows.exists() and gh_workflows.is_dir():
        detected.append("github-actions")

    return detected


def write_project_config(
    project_path: Path,
    modules: list[str],
    platform: str | None = None,
) -> Path:
    """Write .maverick/config.toml for a project."""
    config_dir = project_path / ".maverick"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_file = config_dir / "config.toml"

    lines = [
        "# Maverick project configuration",
        "# Generated by: maverick init",
        "",
        "[modules]",
        "active = [{}]".format(", ".join('"{}"'.format(m) for m in sorted(modules))),
        "",
    ]

    if platform:
        lines.extend([
            "[platform]",
            f'name = "{platform}"',
            "",
        ])

    config_file.write_text("\n".join(lines) + "\n")
    return config_file


def main(args):
    """Entry point called from cli.py."""
    project_path = Path.cwd().resolve()

    # Detect modules
    detected = detect_modules(project_path)

    # Apply overrides
    modules = list(detected)

    if args.override:
        modules = list(args.override)
    if args.add:
        for m in args.add:
            if m not in modules:
                modules.append(m)
    if args.remove:
        modules = [m for m in modules if m not in args.remove]

    # Validate modules
    for m in modules:
        if m not in AVAILABLE_MODULES:
            print(f"Warning: unknown module '{m}'")

    # Display results
    print(f"Project: {project_path}")
    print(f"Detected modules: {', '.join(detected) if detected else '(none)'}")

    if modules != detected:
        print(f"Final modules: {', '.join(modules) if modules else '(none)'}")

    if args.platform:
        print(f"Platform: {args.platform}")

    if args.dry_run:
        print("\nDry run — no files were written.")
        return

    # Write config
    config_file = write_project_config(
        project_path,
        modules,
        platform=args.platform,
    )
    print(f"\nWrote config to: {config_file}")


def clean(dry_run: bool = False) -> None:
    """Remove maverick artifacts from the current project."""
    import shutil

    project_path = Path.cwd().resolve()
    removed = []

    targets = [
        project_path / ".maverick",
        project_path / "docs" / "maverick-audit.md",
    ]

    for target in targets:
        if target.exists():
            if dry_run:
                print(f"Would remove: {target}")
            else:
                if target.is_dir():
                    shutil.rmtree(target)
                else:
                    target.unlink()
                print(f"Removed: {target}")
            removed.append(target)

    if not removed:
        print("Nothing to clean.")
    elif dry_run:
        print(f"\nDry run — {len(removed)} item(s) would be removed.")
